export enum NotificationCategory {
  SIXTY_DAYS_REPORT = 1,
  LEAD_ACTIVITY = 2,
  LEAD_CHANGE_LOG = 3,
  FACILITY_ACTIVITY = 4,
  CORPORATE_ACTIVITY = 5,
  RESIDENT_RENT_INCREASE = 6,
  DATABASE_USER_LOGIN_ACTIVITY = 7,
  LEAD_WEB_EMAIL = 8
}
